version: 2.1

parameters:
  ApiTrigger:
    type: boolean
    default: false

executors:
  node-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.1-jammy
    environment:
      TERM: xterm

commands:

  restore-and-save-cache:
    description: "Restore and save cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run:
          name: Install npm dependencies
          command: npm install --save-dev
      - run:
          name: Install Playwright browsers
          command: npx playwright install
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  run-automation-tests:
    steps:
      - run:
          name: Run Playwright tests
          command: npx playwright test

      - store_artifacts:
          path: playwright-report
          destination: playwright-report

jobs:
  automation-tests-run:
    working_directory: ~/repo
    executor: node-executor
    parameters:
      NightlyRunNotify:
        type: boolean
        default: false
    steps:
      - restore-and-save-cache

      - run:
          name: Export Slack Webhook URL
          command: echo 'export SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL' >> $BASH_ENV

      - run-automation-tests

workflows:
  commit-workflow:
    jobs:
      - automation-tests-run:
          filters:
            branches:
              only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 6 * * 2,4"
          filters:
            branches:
              only:
                - master
    jobs:
      - automation-tests-run

  on-demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - build_approval:
          type: approval
      - automation-tests-run
