version: 2.1

parameters:
  ApiTrigger:
    type: boolean
    default: false

executors:
  node-executor:
    environment:
      TERM: xterm
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.1-focal  # Playwright image с предустановленными браузерами

commands:

  restore-and-save-cache:
    description: "Restore and save cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm install --save-dev
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  run-automation-tests:
    description: "Run automation tests"
    steps:
      - run:
          name: Run automation tests on Chromium
          command: npx playwright test --project=chromium
      - run:
          name: Run automation tests on Firefox
          command: npx playwright test --project=firefox
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

jobs:
  automation-tests-run:
    working_directory: ~/repo
    executor: node-executor
    parameters:
      NightlyRunNotify:
        type: boolean
        default: false
    parallelism: 2
    steps:
      - restore-and-save-cache

      # Slack
      - run:
          name: Export Slack Webhook URL
          command: |
            echo 'export SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL' >> $BASH_ENV

      # Запуск тестов
      - run-automation-tests

workflows:
  commit-workflow:
    jobs:
      - automation-tests-run:
          filters:
            branches:
              only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 6 * * 2,4"
          filters:
            branches:
              only:
                - master
    jobs:
      - automation-tests-run

  on-demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - build_approval:
          type: approval
      - automation-tests-run
