version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16-browsers
    working_directory: ~/repo

jobs:
  install-deps:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  run-playwright-tests:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Playwright tests
          command: npx playwright test
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - install-deps
      - run-playwright-tests:
          requires:
            - install-deps
