version: 2.1

parameters:
  ApiTrigger:
    type: boolean
    default: false

executors:
  node-executor:
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.1-focal
    environment:
      TERM: xterm

commands:

  restore-and-save-cache:
    description: "Restore and save cache"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm install --save-dev
      - run: npx playwright install
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

  run-automation-tests:
    description: "Run automation tests"
    steps:
      - run:
          name: Run all automation tests on Chromium and Firefox
          command: |
            # Run tests but do NOT fail the job
            npx playwright test || true

            # Save exit status
            echo "PW_EXIT_CODE=$?" >> $BASH_ENV

      # Save HTML report
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

      # Run global teardown manually
      - run:
          name: Run Playwright global teardown (Slack)
          command: |
            echo "Exit code: $PW_EXIT_CODE"
            export PW_TEST_EXIT_CODE=$PW_EXIT_CODE
            node ./playwright/global-teardown.js

jobs:
  automation-tests-run:
    working_directory: ~/repo
    executor: node-executor
    parameters:
      NightlyRunNotify:
        type: boolean
        default: false

    steps:
      - restore-and-save-cache

      # Export Slack Webhook
      - run:
          name: Export Slack Webhook URL
          command: echo 'export SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL' >> $BASH_ENV

      - run-automation-tests

workflows:
  commit-workflow:
    jobs:
      - automation-tests-run:
          filters:
            branches:
              only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 6 * * 2,4"
          filters:
            branches:
              only:
                - master
    jobs:
      - automation-tests-run

  on-demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - build_approval:
          type: approval
      - automation-tests-run
